
import { Car } from './types';

export const THEME_GREEN = '#2A4E2F';
export const THEME_GREEN_DARK = '#1D3621';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    brand: 'Dacia',
    model: 'Logan',
    year: 2022,
    city: 'Casablanca',
    price_per_day: 253,
    deposit: 5000,
    category: 'Economy',
    transmission: 'Manuelle',
    fuel_type: 'Diesel',
    seats: 5,
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop',
    agency_name: 'Agence-68caed2654',
    agency_id: 'ag1',
    rating: 5.0,
    reviews_count: 0,
    location_lat: 33.5731,
    location_lng: -7.5898,
    is_verified_partner: true,
  },
  {
    id: '2',
    brand: 'Dacia',
    model: 'Logan',
    year: 2023,
    city: 'Casablanca',
    price_per_day: 253,
    deposit: 5000,
    category: 'Economy',
    transmission: 'Manuelle',
    fuel_type: 'Diesel',
    seats: 5,
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop',
    agency_name: 'Agence-68caed2654',
    agency_id: 'ag1',
    rating: 5.0,
    reviews_count: 0,
    location_lat: 33.5731,
    location_lng: -7.5898,
    is_verified_partner: true,
  },
  {
    id: '3',
    brand: 'Dacia',
    model: 'Logan',
    year: 2025,
    city: 'Casablanca',
    price_per_day: 253,
    deposit: 5000,
    category: 'Economy',
    transmission: 'Manuelle',
    fuel_type: 'Diesel',
    seats: 5,
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop',
    agency_name: 'Agence-68caed2654',
    agency_id: 'ag1',
    rating: 5.0,
    reviews_count: 0,
    location_lat: 33.5731,
    location_lng: -7.5898,
    is_verified_partner: true,
  },
  {
    id: '4',
    brand: 'Dacia',
    model: 'Sandero Streetway',
    year: 2024,
    city: 'Casablanca',
    price_per_day: 253,
    deposit: 5000,
    category: 'Economy',
    transmission: 'Manuelle',
    fuel_type: 'Diesel',
    seats: 5,
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop',
    agency_name: 'Agence-68caed2654',
    agency_id: 'ag1',
    rating: 5.0,
    reviews_count: 0,
    location_lat: 33.5731,
    location_lng: -7.5898,
    is_verified_partner: true,
  },
  {
    id: '5',
    brand: 'Dacia',
    model: 'Sandero Streetway',
    year: 2025,
    city: 'Casablanca',
    price_per_day: 253,
    deposit: 5000,
    category: 'Economy',
    transmission: 'Manuelle',
    fuel_type: 'Diesel',
    seats: 5,
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop',
    agency_name: 'Agence-68caed2654',
    agency_id: 'ag1',
    rating: 5.0,
    reviews_count: 0,
    location_lat: 33.5731,
    location_lng: -7.5898,
    is_verified_partner: true,
  }
];

export const CATEGORIES: { label: string; icon?: string }[] = [
  { label: 'Economy' },
  { label: 'Standard' },
  { label: 'SUV / 4x4' },
  { label: 'Luxury' },
  { label: 'Luxury SUV' },
  { label: 'Van / MPV' },
  { label: 'Minibus' },
  { label: 'Sport' },
];

export const CITIES = [
  { name: 'Casablanca', desc: 'Economic capital of Morocco', icon: 'building' },
  { name: 'Casablanca - Aéroport Mohammed V', desc: 'Main Casablanca airport hub', icon: 'plane' },
  { name: 'Rabat', desc: 'Capital city, rich in culture', icon: 'building' },
  { name: 'Rabat - Aéroport', desc: 'Airport access near Rabat/Salé', icon: 'plane' },
  { name: 'Fes', desc: 'Historic and spiritual heart', icon: 'landmark' },
  { name: 'Fes - Aéroport', desc: 'Airport access', icon: 'plane' },
  { name: 'Marrakech', desc: 'The Red City, heart of tourism', icon: 'landmark' },
  { name: 'Tangier', desc: 'The gateway to Africa', icon: 'building' },
  { name: 'Agadir', desc: 'Premier beach resort city', icon: 'landmark' },
  { name: 'Tétouan', desc: 'The White Dove', icon: 'landmark' },
];

export const TIMES = Array.from({ length: 48 }, (_, i) => {
  const hours = Math.floor(i / 2);
  const minutes = i % 2 === 0 ? '00' : '30';
  return `${String(hours).padStart(2, '0')}:${minutes}`;
});
